### ISSUE TITLE
better word count with dqbd/tiktoken

### ISSUE THREAD

**Issue by ahxxm** [alondmnt/joplin-plugin-jarvis#10]
it's OpenAI models' tokenizer, allowing a precise split
the pure js version is not small, its unpack size is 10M https://www.npmjs.com/package/js-tiktoken

**Comment by alondmnt** [comment]
Thanks for the suggestion! I'll have a look at it. However, since I recently added many models other than OpenAI's, it makes it harder to maintain support for many tokenizers. Perhaps I'll add it in the future, but for now I'll keep an approximated token count.
