### ISSUE TITLE
chat with your notes - stuck at Generating notes response...

### ISSUE THREAD

**Issue by benintech** [alondmnt/joplin-plugin-jarvis#13]
I create a new note, and select "Chat with your notes". I got then stuck :

![Screenshot from 2023-08-20 14-49-46](https://github.com/alondmnt/joplin-plugin-jarvis/assets/5140169/3ea67fd1-0bd5-418e-b9e7-e474137b91c7)

Note :
- I verified that `Universal Sentence Encoder.sqlite` has been created
- My setup is quite small (<100 notes)
- Using Linux/Flatpak

**Comment by alondmnt** [comment]
Thanks for the feedback.

I can reproduce the scenario with an empty note. I'll check why in this case there is no response from the model, and add a safeguard if needed.

But please try the following: write a prompt to the model and then select "Chat with your notes". The model should response in this case, using information from your own notes, unless there is some other issue.
