### ISSUE TITLE
Feature request: Please allow API from text-generation-webui

### ISSUE THREAD

**Issue by SmoothBrainApe** [alondmnt/joplin-plugin-jarvis#15]
Hi,

I want to try connecting Jarvis using oobabooga/text-generation-webui as a backend instead of openai for private and offline solution. Is that possible? Thanks!

**Comment by alondmnt** [comment]
I believe this should be possible with the current version of Jarvis. Follow the instructions [here](https://github.com/alondmnt/joplin-plugin-jarvis/blob/master/GUIDE.md#offline-chat-model-with-lm-studio), but use the following URL for `Chat: Custom model API endpoint`: http://127.0.0.1:5000/v1/chat/completions (based on [this example](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#examples))
