### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by MRP0E** [alondmnt/joplin-plugin-jarvis#16]
It would be an awesome feature for Jarvis to use a local LLM via [Ollama](https://github.com/jmorganca/ollama).

**Comment by alondmnt** [comment]
I will look into it (no promises).
Meanwhile, we currently support the local [GPT4All](https://github.com/alondmnt/joplin-plugin-jarvis/blob/master/GUIDE.md#offline-chat-model-with-gpt4all) and [LM Studio](https://github.com/alondmnt/joplin-plugin-jarvis/blob/master/GUIDE.md#offline-chat-model-with-lm-studio).

**Comment by MRP0E** [comment]
@danielw2904 Thats awesome. Thank for the doc. Will try it asap.
