### ISSUE TITLE
Allow excluding or including by notebook?

### ISSUE THREAD

**Issue by smach** [alondmnt/joplin-plugin-jarvis#21]
Thanks for the plugin, which looks very interesting! It would be useful if I could exclude an entire notebook by notebook - or conversely designate which notebooks I want included - and not only by individual note. I have a huge notebook that I wouldn't want to include. If I modify all thousands of notes in there to add the exclude tag, all the notes will show that new modification date.

**Comment by alondmnt** [comment]
I think that it's already covered. Try this:
<img width="553" alt="image" src="https://github.com/alondmnt/joplin-plugin-jarvis/assets/17462125/495bc743-d9ef-41df-b37f-9e0cbd1b42a0">

**Comment by smach** [comment]
Hi thank you very much. It was strange, the first time I installed it I didn't see any menu options even after restarting Joplin, I needed to deactivate and reactivate. Quick question: If I select "Include notebook from note DB" for a few notebooks, does that mean only those notebooks are included? Or should I make sure to manually exclude and include each one?

**Comment by alondmnt** [comment]
The `include` command is meant to undo exclusion. So if you want to include specific notebooks, you'll have to exclude all others. Exclusion also excludes every sub-notebook within the notebook that you selected
