### ISSUE TITLE
Clearly document exactly which data is sent for each type of query

### ISSUE THREAD

**Issue by chr15m** [alondmnt/joplin-plugin-jarvis#25]
Thank you for building and sharing this software!

As a potential user of this plugin I feel nervous about having my entire second brain uploaded to a third party service. I like the idea of doing simple chats though. What I would like to see in the documentation is a separate, clear, standardised indication of which data is uploaded for each of the types of queries listed.

For example:

- Chat:
 - Start a new note, or continue an existing conversation in a saved note. Place the cursor after your prompt and run the command Chat with Jarvis (from the toolbar or Tools/Jarvis menu). Each time you run the command Jarvis will append its response to the note at the current cursor position (given the previous content that both of you created). If you don't like the response, run the command again to replace it with a new one.
 - *Data shared:* Only the current note you are in.

Not sure if the above 'Data shared' annotation is actually correct, which is why I think it should be clearer to the user. I'm happy to submit a PR implementing this if you can let me know the details of the data shared. Thank you!

**Comment by alondmnt** [comment]
Understand your concerns. I can add something, probably in a separate section that is clearly indicated in the main README. However if this wasn't clear, what is sent to the model is:

1. Any command: Your prompt.
2. Research command: (1) + Paper abstracts found online.
3. Chat commands: The last [memory tokens] of the current note up to the current position of the cursor.
4. Chat with notes commands: (3) + Note excerpts (each up to [notes max tokens] long, for a total of [memory tokens]) that are similar to the current context of the conversation.
5. Embeddings (computed offline locally by default): All of your notes.

BTW, you can host everything offline on your laptop without sending any bit to a third party (see the [guide](https://github.com/alondmnt/joplin-plugin-jarvis/blob/master/GUIDE.md)).

**Comment by chr15m** [comment]
Fantastic that is very clear, thank you so much!

**Comment by alondmnt** [comment]
Updated the README.
