### ISSUE TITLE
OpenAI proxy

### ISSUE THREAD

**Issue by LevonLu** [alondmnt/joplin-plugin-jarvis#26]
Hello, could you please add an option to customize the OpenAI proxy in the settings?

**Comment by alondmnt** [comment]
I'm not entirely sure what you mean by OpenAI proxy, but if it's [this repo](https://github.com/UNICKCHENG/openai-proxy), and it supports the OpenAI API, then you can change the OpenAI endpoint already in the settings.

For example (just guessing here), select the following settings:

Chat: Model
online) OpenAI or compatible: custom model

**and in the advanced settings:**

Chat: OpenAI (or compatible) custom model ID
gpt-4

Chat: Custom model is a conversation model
yes

Chat: Custom model API endpoint
https://github.com/UNICKCHENG/openai-proxy
