### ISSUE TITLE
Supports ollama/lm studio/chat4all  local llm

### ISSUE THREAD

**Issue by icursor** [alondmnt/joplin-plugin-jarvis#27]

**Comment by alondmnt** [comment]
There is already support for [LM Studio](https://github.com/alondmnt/joplin-plugin-jarvis/blob/master/GUIDE.md#offline-chat-model-with-lm-studio), [Ollama](https://github.com/alondmnt/joplin-plugin-jarvis/blob/master/GUIDE.md#offline-chat-model-with-ollama) and other local LLMs (see linked guide).
