### ISSUE TITLE
Feature Request: ChatGPT 4o mini

### ISSUE THREAD

**Issue by kacperpaluch** [alondmnt/joplin-plugin-jarvis#30]
Go you have any plans to add support for ChatGPT 4o mini? It's cheaper and better than ChatGPT 3.5

**Comment by alondmnt** [comment]
I'm about to make it the default model in the next release, soon. You can already use it by choosing `Open AI or compatible: custom model` and setting `Chat: OpenAI (or compatible) custom model ID` to `gpt-4o-mini`.
